Each peer creates a goroutine to discover
alecbcs/hyprspace pull request #84
Opened 2022-07-04 04:49 UTC by QZAiXH

FindPeer takes more time to search, and using for loop will lead to longer search time

2022-07-12 02:21 UTC, QZAiXH commented
ping @alecbcs

2022-07-12 19:09 UTC, alecbcs requested changes
Pong?

All jokes aside, hello! Apologies for missing this one, I took a couple of months off this summer while traveling and you caught me right at the end of that trip. Anyway thanks for the pull request! This looks good but I have a couple of concerns.

You're right that this will be faster to discover peers, but given an interface that has N peers you're also now going to be creating N time tickers instead of just the one that was created before. This means hyprspace is going to eat up more RAM as well as background CPU cycles for users with more peers. My argument would be to sacrifice a bit of speed for improved performance but maybe there's a better middle ground?

2022-07-12 19:09 UTC, alecbcs commented on p2p/discover.go
> +				fmt.Printf("[+] Connection to %s Successful. Network Ready.\n", ip)
Although this simplifies the code base, it is generally bad form to include `print` statements in a non-cli library that someone might want to use in their own application making use of hyprspace. This is why I originally split off the pretty discovery code as a function within the cli library.

2022-07-14 07:05 UTC, QZAiXH commented
> 

Yes, you are correct, we should manage the number of goroutines. I will modify it later.

2024-03-11 14:08 UTC, closed without merging